services:
  web:
    image: gitlab.dockerbuch.info/dockerbuch/dockerbuch-web:dev
    build:
      context: .
      target: build
    user: "${UID}:${GID}"

    command: ["hugo", "server", "--bind", "0.0.0.0"]
    ports:
      - 1313:1313
    volumes:
      - ./dockerbuch.info:/src

