services:
  api:
    build: ./api
    ports:
      - "127.0.0.1:8088:8088"
    networks:
      - backend_net
      - frontend_net
    depends_on:
      - backend

  backend:
    build: ./backend
    networks:
      - backend_net

networks:
  backend_net:
    # driver:   bridge
    internal: true
  frontend_net:
    # driver:   bridge
